# SQL Server Database Configuration
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=OnlineExamDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=springuser
spring.datasource.password=Spring@123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Gmail SMTP Configuration for OTP Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=onlineexaminationportal1@gmail.com
spring.mail.password=zgkk vnss fppx iagt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.application.name=online-examination-system

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
logging.level.org.springframework.security=ERROR

server.address=0.0.0.0