spring.application.name=online-examination-system

# MySQL Railway Database Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thymeleaf
spring.thymeleaf.cache=false

# Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=onlineexaminationportal1@gmail.com
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false

# Disable default Spring Security login
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
logging.level.org.springframework.security=ERROR

server.port=${PORT:8080}
server.address=0.0.0.0