spring.application.name=online-examination-system

# MySQL Railway Database Configuration
spring.datasource.url=jdbc:mysql://zephyr.proxy.rlwy.net:48224/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=qdZSNCbORSILrBuJHIlSlLHXWsJlCjYv
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thymeleaf
spring.thymeleaf.cache=false

# Gmail SMTP Configuration
#spring.mail.host=smtp-relay.brevo.com
#spring.mail.port=587
#spring.mail.username=acbe4d001@smtp-brevo.com
#spring.mail.password=d0M2RH8Qb54nG6SX
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.ssl.enable=false

# Disable default Spring Security login
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
logging.level.org.springframework.security=ERROR

brevo.api.key=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

server.port=${PORT:8080}
server.address=0.0.0.0